DefaultContentLanguage = "pt-br"
title = "Blog do Diego Eis"
baseURL = "https://diegoeis.com/"
theme = "diegoeis-v2"

# disqusShortname = "tableless"
googleAnalytics = "UA-66489393-1"

enableRobotsTXT = true
disableLiveReload = true

[params]
  siteName = "diegoeis.com"
  description = "Site do Diego Eis"
  githubUsername = "diegoeis"
  twitterUsername = "diegoeis"
  tagline = "Textos e artigos do Diego Eis"

[permalinks]
  posts = "/:filename"
  pages = "/:filename"

[taxonomies]
  tag = "tags"
