DefaultContentLanguage = "pt-br"
title = "Blog do Diego Eis"
baseURL = "https://diegoeis.com/"
theme = "diegoeis-v3"
languageCode = "pt-br"
removePathAccents = true

summaryLength = 20

enableRobotsTXT = true
disableLiveReload = false
disableKinds = ["section"]

rssLimit = 40
pygmentsUseClasses=true
assetDir = "/static/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  siteName = "diegoeis.com"
  AuthorName = "Diego Eis"
  description = "Blog pessoal do Diego Eis"
  Subtitle = "Meu blog."
  githubUsername = "diegoeis"
  twitterUsername = "diegoeis"
  tagline = "Textos e artigos do Diego Eis"

[permalinks]
  posts = "/:filename"
  pages = "/:filename"

[taxonomies]
  tag = "tags"
  category = "categories"

[imaging]
  quality = 75


[related]
  threshold = 100
  includeNewer = true
  toLower = false

  [[related.indices]]
  name  = "tags"
  weight = 40
  [[related.indices]]
  name  = "title"
  weight = 40
