DefaultContentLanguage = "pt-br"
title = "Blog do Diego Eis"
baseURL = "https://diegoeis.com/"
theme = "diegoeis-v2"
languageCode = "pt-br"

enableRobotsTXT = true
disableLiveReload = true

rssLimit = 40

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  siteName = "diegoeis.com"
  AuthorName = "Diego Eis"
  description = "Blog pessoal do Diego Eis"
  Subtitle = "Meu blog."
  githubUsername = "diegoeis"
  twitterUsername = "diegoeis"
  tagline = "Textos e artigos do Diego Eis"

[permalinks]
  posts = "/:filename"
  pages = "/:filename"

[taxonomies]
  tag = "tags"
  category = "categories"

[imaging]
  quality = 75