name = "diegoeis-v3"
license = "MIT"
description = "Diego Eis 2019 v3"
homepage = "http://diegoeis.com/"
tags = []
features = []
min_version = .2

[author]
  name = "Diego Eis"
  homepage = "http://diegoeis.com"
