name = "diegoeis-v4"
license = "MIT"
description = "Diego Eis 2019/2020 - v4"
homepage = "http://diegoeis.com/"
tags = []
features = []

[author]
  name = "Diego Eis"
  homepage = "http://diegoeis.com"
