name = "diegoeis-v2"
license = "MIT"
description = "Diego Eis 2019"
homepage = "http://diegoeis.com/"
tags = []
features = []
min_version = .1

[author]
  name = "Diego Eis"
  homepage = "http://diegoeis.com"
